"use strict";

/**
 * Shared filesystem-walk exclusions for the WarpOS manifest tools.
 *
 * build.js (writes _warpos/MANIFEST.json) and validate.js (checks that manifest
 * against disk) MUST agree on what is *not shipped*, or they drift: build skips a
 * path, validate then reports the same path "unmanifested", and BC-02
 * (Manifest coverage/honesty drift) reds.
 *
 * Historically each file kept its own copy of these sets and they diverged
 * (`WarpOS-Update`, then `_planning` — added to the builder, missing from the
 * validator). One source makes divergence impossible: the two tools can't
 * disagree about the skip set if there is only one skip set. This is the
 * named enforcer for the duplication-drift bug class (CLAUDE.md § Refactor &
 * Rename Hygiene) — the constant is the source of truth; both tools read it.
 */

// Directories (matched by basename, at any depth) never enumerated in the
// shipping manifest: package/build caches, VCS, IDE config, agent/operator
// scratch, and transient runtime state.
const WALK_SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  ".warpos",
  ".warpos-backup",
  "WarpOS-Update", // gitignored operator scratch (parallels .warpos); not framework
  ".vscode",
  ".idea",
  "runtime",
  "worktrees", // .claude/worktrees/ — agent scratch clones; not framework
  ".worktrees", // repo-root builder isolation worktrees (.worktrees/wt-*) — agent scratch; never framework, must never enter the shipping manifest nor break its build
  "_planning", // operator planning scratch for in-flight system updates; not framework, not shipped
  "_reports", // per-project report OUTPUT (sprint/milestone/session/checkpoint reports via /report); created on use like runtime/ — NOT framework content. The /report skill (.claude/commands/) + framework/templates/report/ ship and seed it; the emitted reports themselves never ship. (SP-20260531-001)
  "agent-memory", // .claude/agent-memory/<teammate>/ — per-agent teammate memory store (e.g. Beta's accumulated judgment); runtime/local like the home memory dir + gitignored, NOT framework content. Without this skip the builder can't classify it and the build fails (session-end 2026-06-05).
]);

// Individual files never enumerated in the shipping manifest.
const WALK_SKIP_FILES = new Set([
  ".env",
  ".env.local",
  "DUMP.md",
  // Transient/local root docs — operator input specs + per-repo registers, NOT
  // shipped framework (same class as DUMP.md). WARPOS.md is a per-repo gap register
  // (products generate their own via /warp:flag; canonical's is local, never shipped);
  // WARPOS-ISSUES.md is a session issue log; the *-PROMPT.md files are operator input.
  "WARPOS.md",
  "WARPOS-ISSUES.md",
  // NOTAGAIN.md — operator-facing dispatch-failure diagnostic (2026-06-10), same
  // per-repo-operator-doc class as DUMP.md/WARPOS.md; never framework content.
  "NOTAGAIN.md",
  // DISPATCH-ERRORS.md — operator-directed dispatch-failure census + redesigns
  // (2026-06-11), companion to NOTAGAIN.md; same per-repo-operator-doc class.
  "DISPATCH-ERRORS.md",
  "WARPOS-PROMPT.md",
  "MASTERCONSOLE-PROMPT.md",
  ".DS_Store",
  "Thumbs.db",
  // Transient per-session markers hooks write under .claude/ (gitignored). They
  // are NOT framework content; both build.js and validate.js read this one set,
  // so listing them here keeps the two in agreement and stops the "session marker
  // flaps the validate gate → BC-02 reds the release" class (hit during 0.13.1).
  ".session-start-commit",
  ".session-checkpoint.json",
  // Harness scheduled-wakeup lock (.claude/scheduled_tasks.lock) — transient
  // per-session state written by the Claude Code scheduler (first seen 2026-06-10
  // when a session used ScheduleWakeup). Same class as the session markers above.
  "scheduled_tasks.lock",
  // Coherence graph — regenerated by scripts/system/coherence.js on every run
  // (content-stable; generatedAt preserved when unchanged). Untracked and not
  // gitignored, so without this skip it appears "unmanifested" the moment
  // coherence runs and flaps validate --strict (same class as the session
  // markers above). build.js + validate.js read this one set, so they stay
  // in agreement.
  "system-coherence.graph.json",
]);

module.exports = { WALK_SKIP_DIRS, WALK_SKIP_FILES };
