#!/usr/bin/env bash
# install-git-hooks.sh — wire project git hooks into .git/hooks.
#
# Idempotent. Run once per clone. If a matching hook already exists and
# isn't ours (no marker line), we back it up with .pre-alex-YYYYMMDD suffix
# before overwriting.
#
# Installed:
#   pre-commit → runs scripts/hooks/pre-commit-steps-check.js + scripts/hooks/pre-commit-check-lib.js
#                (SP-20260720-002 Seam D consumer b: check-lib fast, NON-AUTHORITATIVE local feedback —
#                bypassable via --no-verify; the real gate is trusted-controller.js's out-of-tree pinned run)
#   reference-transaction → runs scripts/hooks/protected-ref-transaction.js (SP-20260720-002 Seam E: the
#                sole-route MECHANISM for refs/heads/main — probe-confirmed to fire on every write surface
#                and to ABORT on a non-zero 'prepared'-phase exit; NOT bypassed by --no-verify. See
#                runtime/sp002-phase4/reftxn-probe-evidence.md)
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
HOOKS_DIR="$REPO_ROOT/.git/hooks"
MARKER="# alex-pre-commit-steps-check"
REFTXN_MARKER="# alex-protected-ref-transaction"

mkdir -p "$HOOKS_DIR"

TARGET="$HOOKS_DIR/pre-commit"

# Backup any existing non-ours hook
if [ -f "$TARGET" ] && ! grep -q "$MARKER" "$TARGET" 2>/dev/null; then
  BACKUP="$TARGET.pre-alex-$(date +%Y%m%d%H%M%S)"
  cp "$TARGET" "$BACKUP"
  echo "Backed up existing pre-commit → $BACKUP"
fi

cat > "$TARGET" <<'HOOK'
#!/usr/bin/env bash
# alex-pre-commit-steps-check
# Auto-generated by scripts/install-git-hooks.sh — safe to regenerate.
# Blocks commits that break _requirements/00-canonical/STEPS.json schema OR leave
# the canonical step-table docs drifted from STEPS.json. ALSO runs the check-lib
# fast-feedback pass (SP-20260720-002 Seam D consumer b) — NON-AUTHORITATIVE,
# bypassable via --no-verify; the real integration gate is trusted-controller.js
# (Seam B) fenced by the reference-transaction hook (Seam E), never this file.
set -e

REPO_ROOT=$(git rev-parse --show-toplevel)
SCRIPT="$REPO_ROOT/scripts/hooks/pre-commit-steps-check.js"
CHECKLIB_SCRIPT="$REPO_ROOT/scripts/hooks/pre-commit-check-lib.js"

# Prefer node from PATH; give a clear error if absent.
if ! command -v node >/dev/null 2>&1; then
  echo "pre-commit: node not found on PATH — cannot validate STEPS.json" >&2
  exit 1
fi

if [ -f "$SCRIPT" ]; then
  node "$SCRIPT"
else
  # If the validator is missing, don't block — warn and let the commit through.
  # (A fresh clone without scripts/ checked out should not be strangled.)
  echo "pre-commit: $SCRIPT missing — skipping steps check" >&2
fi

if [ -f "$CHECKLIB_SCRIPT" ]; then
  node "$CHECKLIB_SCRIPT"
else
  echo "pre-commit: $CHECKLIB_SCRIPT missing — skipping check-lib fast feedback" >&2
fi
HOOK

chmod +x "$TARGET"
echo "Installed pre-commit → $TARGET"
echo "It runs node $REPO_ROOT/scripts/hooks/pre-commit-steps-check.js + pre-commit-check-lib.js"

# ── reference-transaction (SP-20260720-002 Seam E: the sole-route MECHANISM for refs/heads/main) ──────────
REFTXN_TARGET="$HOOKS_DIR/reference-transaction"

if [ -f "$REFTXN_TARGET" ] && ! grep -q "$REFTXN_MARKER" "$REFTXN_TARGET" 2>/dev/null; then
  BACKUP="$REFTXN_TARGET.pre-alex-$(date +%Y%m%d%H%M%S)"
  cp "$REFTXN_TARGET" "$BACKUP"
  echo "Backed up existing reference-transaction → $BACKUP"
fi

cat > "$REFTXN_TARGET" <<'HOOK'
#!/usr/bin/env bash
# alex-protected-ref-transaction
# Auto-generated by scripts/install-git-hooks.sh — safe to regenerate.
# SP-20260720-002 Seam E: the sole-route MECHANISM for refs/heads/main. Probe-confirmed
# (runtime/sp002-phase4/reftxn-probe-evidence.md, git 2.54.0.windows.1) to fire on every
# write surface (commit, update-ref, fast-forward, non-ff merge) and to ABORT the
# transaction on a non-zero exit in the 'prepared' phase — and NOT bypassed by
# --no-verify. Requires the current trusted-controller fencing token (set ONLY around
# trusted-controller.js's own commitIntegration call); absent/invalid -> refused (git
# aborts the write). Named-uncovered, operator-DROPPED (hostile-shell, out of scope):
# core.hooksPath redirect, hook deletion, a direct .git/refs/** filesystem write.
set -e

# ED-261: resolve the verifier via the COMMON git dir (shared across ALL worktrees), NOT the active
# worktree toplevel. Worktrees share this hook (common .git/hooks) but each has its own toplevel; a
# pre-fence-era worktree checkout lacks scripts/hooks/protected-ref-transaction.js, so the old
# "git rev-parse --show-toplevel" + exit-0-on-missing SILENTLY SKIPPED the fence for a refs/heads/main
# write issued from that cwd. The common git dir points at the canonical checkout that installed it.
REPO_ROOT_COMMON=$(cd -- "$(git rev-parse --git-common-dir 2>/dev/null)" 2>/dev/null && pwd)
REPO_ROOT=$(dirname -- "$REPO_ROOT_COMMON")
SCRIPT="$REPO_ROOT/scripts/hooks/protected-ref-transaction.js"

# reference-transaction feeds old/new/ref lines on stdin -- a SINGLE-READ stream. Buffer it once so
# we can both (a) decide protected-vs-not when the verifier is unavailable and (b) re-feed it below.
STDIN_BUF=$(cat)
touches_protected() {
  printf '%s\n' "$STDIN_BUF" | grep -qE '(^|[[:space:]])refs/heads/main([[:space:]]|$)'
}

if [ ! -f "$SCRIPT" ] || ! command -v node >/dev/null 2>&1; then
  # Verifier unavailable (missing script -- pre-fence-era/bare checkout -- or no node on PATH).
  # FAIL CLOSED for a protected ref; graceful-skip ONLY for non-protected (a bare clone must not
  # strangle non-main writes -- the honest ceiling stays honest for the non-protected case only).
  if touches_protected; then
    echo "reference-transaction: verifier unavailable AND a protected ref (refs/heads/main) touched -- REFUSING (fail-closed, ED-261)" >&2
    exit 1
  fi
  echo "reference-transaction: verifier unavailable (no protected ref touched) -- skipping" >&2
  exit 0
fi

# Re-feed the buffered stdin to the verifier (the stream was consumed above). node's exit is the hook
# exit; a non-zero in the 'prepared' phase ABORTS the write.
printf '%s\n' "$STDIN_BUF" | node "$SCRIPT" "$@"
HOOK

chmod +x "$REFTXN_TARGET"
echo "Installed reference-transaction → $REFTXN_TARGET"
echo "It runs node $REPO_ROOT/scripts/hooks/protected-ref-transaction.js (Seam E)"
