#!/usr/bin/env node
"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const path = require("path");
const { execFileSync } = require("child_process");

const {
  loadRegistry,
  loadBaseline,
  checkRegistryRegressions,
  checkNewEntrants,
  computeCoverage,
  runEnforcer,
} = require("./gate-failclosed-enforcer.js");

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const FIXTURES = path.join(REPO_ROOT, "runtime", "enforcer-fixtures", "SP-20260829-001");

test("real registry loads, all 13 rows carry provenance + quote for manual dispositions", () => {
  const registry = loadRegistry(path.join(__dirname, "gate-failclosed-registry.json"));
  assert.equal(registry.rows.length, 13);
  for (const row of registry.rows) {
    assert.equal(row.polarity_provenance, "manual-by-read");
    assert.ok(row.decision_semantics_quote && row.decision_semantics_quote.length > 10);
    assert.ok(["defect", "not-a-defect", "not-a-gate", "contested", "untriaged"].includes(row.disposition));
  }
});

test("real baseline loads and is a committed snapshot (never regenerated by the loader)", () => {
  const baseline = loadBaseline(path.join(__dirname, "gate-failclosed-baseline.json"));
  assert.ok(baseline.site_ids.length > 0);
  assert.equal(baseline.site_ids.length, baseline.site_count);
});

// ---------------------------------------------------------------------------
// S6-6a: DEMONSTRATE BY EXECUTION that a registry-member regression is
// caught. b2-regressed-registry.json's one row claims expected_finding:
// "absent" (believed repaired); b2-regressed-site.js still contains the
// permissive catch at the stated line. checkRegistryRegressions() must
// report it, and running it standalone must be non-empty.
// ---------------------------------------------------------------------------
test("S6-6a: registry member marked repaired but still fail-open IS caught (regression)", () => {
  const registry = loadRegistry(path.join(FIXTURES, "b2-regressed-registry.json"));
  const { regressed, checkedRepaired } = checkRegistryRegressions(registry.rows, FIXTURES);
  assert.equal(checkedRepaired.length, 1);
  assert.equal(checkedRepaired[0].checked, true);
  assert.equal(checkedRepaired[0].permissive, true);
  assert.equal(regressed.length, 1);
  assert.equal(regressed[0].site_id, "b2-regressed-site.js:11");
});

test("S6-6a control: same check on the REAL registry (nothing marked repaired yet) finds zero regressions", () => {
  const registry = loadRegistry(path.join(__dirname, "gate-failclosed-registry.json"));
  const { regressed, checkedRepaired } = checkRegistryRegressions(registry.rows, REPO_ROOT);
  assert.equal(checkedRepaired.length, 0); // none of the 13 seeded rows claim expected_finding: absent yet
  assert.equal(regressed.length, 0);
});

// ---------------------------------------------------------------------------
// S6-6b: DEMONSTRATE BY EXECUTION that a new untriaged terminal-decision
// site is caught. fresh-hook.js is a real catch->process.exit(0) site;
// b2-empty-baseline.json deliberately excludes it.
// ---------------------------------------------------------------------------
test("S6-6b: a new terminal-decision site not in the baseline IS caught (untriaged entrant)", () => {
  const baseline = loadBaseline(path.join(FIXTURES, "b2-empty-baseline.json"));
  const root = path.join(FIXTURES, "b2-new-entrant-root");
  const { newEntrants, currentSiteIds } = checkNewEntrants(root, new Set(baseline.site_ids));
  assert.ok(currentSiteIds.length >= 1, "the fixture root must yield at least one live finding");
  assert.equal(newEntrants.length, currentSiteIds.length, "an empty baseline means every live finding is a new entrant");
  assert.ok(newEntrants.some((id) => id.endsWith("fresh-hook.js:12")));
});

test("S6-6b control: baseline that DOES contain the site yields zero new entrants", () => {
  const root = path.join(FIXTURES, "b2-new-entrant-root");
  const { currentSiteIds } = checkNewEntrants(root, new Set());
  const knownBaseline = new Set(currentSiteIds); // pretend we'd already captured exactly this set
  const { newEntrants } = checkNewEntrants(root, knownBaseline);
  assert.equal(newEntrants.length, 0);
});

// ---------------------------------------------------------------------------
// End-to-end CLI executions — the actual exit codes a caller would observe.
// ---------------------------------------------------------------------------
test("S6-6 END-TO-END (a): CLI run with the regressed fixture registry exits non-zero", () => {
  let exitCode = 0;
  let stdout = "";
  try {
    stdout = execFileSync(
      process.execPath,
      [
        path.join(__dirname, "gate-failclosed-enforcer.js"),
        "--root",
        path.join(FIXTURES, "b2-new-entrant-root"), // avoid mixing in the new-entrant failure mode by pointing --root at a root whose one site we treat as baseline-known below
        "--registry",
        path.join(FIXTURES, "b2-regressed-registry.json"),
        "--baseline",
        path.join(FIXTURES, "b2-fresh-hook-only-baseline.json"),
        "--base-dir",
        FIXTURES,
      ],
      { encoding: "utf8" },
    );
  } catch (e) {
    exitCode = e.status;
    stdout = e.stdout || "";
  }
  const parsed = JSON.parse(stdout);
  assert.equal(exitCode, 1, "observed exit code for the regression-only CLI run");
  assert.equal(parsed.status, "blocked");
  assert.equal(parsed.regressed.length, 1);
  assert.equal(parsed.new_entrants.length, 0, "the paired baseline covers fresh-hook.js, isolating the regression failure mode");
});

test("S6-6 END-TO-END (b): CLI run with the empty baseline (new entrant) exits non-zero", () => {
  let exitCode = 0;
  let stdout = "";
  try {
    stdout = execFileSync(
      process.execPath,
      [
        path.join(__dirname, "gate-failclosed-enforcer.js"),
        "--root",
        path.join(FIXTURES, "b2-new-entrant-root"),
        "--registry",
        path.join(FIXTURES, "b2-clean-registry.json"),
        "--baseline",
        path.join(FIXTURES, "b2-empty-baseline.json"),
        "--base-dir",
        FIXTURES,
      ],
      { encoding: "utf8" },
    );
  } catch (e) {
    exitCode = e.status;
    stdout = e.stdout || "";
  }
  const parsed = JSON.parse(stdout);
  assert.equal(exitCode, 1, "observed exit code for the new-entrant-only CLI run");
  assert.equal(parsed.status, "blocked");
  assert.equal(parsed.regressed.length, 0, "the clean registry has no expected_finding:absent rows, isolating the new-entrant failure mode");
  assert.ok(parsed.new_entrants.length >= 1);
});

test("S6-6 END-TO-END (c): CLI run with a matched, clean baseline+registry exits ZERO (no-op mutation guard)", () => {
  let exitCode = 0;
  let stdout = "";
  try {
    stdout = execFileSync(
      process.execPath,
      [
        path.join(__dirname, "gate-failclosed-enforcer.js"),
        "--root",
        path.join(FIXTURES, "b2-new-entrant-root"),
        "--registry",
        path.join(FIXTURES, "b2-clean-registry.json"),
        "--baseline",
        path.join(FIXTURES, "b2-fresh-hook-only-baseline.json"),
        "--base-dir",
        FIXTURES,
      ],
      { encoding: "utf8" },
    );
  } catch (e) {
    exitCode = e.status;
    stdout = e.stdout || "";
  }
  const parsed = JSON.parse(stdout);
  assert.equal(exitCode, 0, "a run whose baseline already covers the only live site, with nothing claiming repair, must be green");
  assert.equal(parsed.status, "ok");
});

test("computeCoverage: phrasing derives every number from the emitted table (real registry + real baseline)", () => {
  const registry = loadRegistry(path.join(__dirname, "gate-failclosed-registry.json"));
  const baseline = loadBaseline(path.join(__dirname, "gate-failclosed-baseline.json"));
  const coverage = computeCoverage(registry.rows, baseline);
  assert.equal(coverage.M, baseline.site_ids.length);
  assert.ok(coverage.N >= 0 && coverage.N <= coverage.M);
  assert.ok(coverage.K >= 0 && coverage.K <= coverage.M);
  assert.ok(coverage.phrasing.includes(String(coverage.M)));
  assert.ok(coverage.phrasing.includes(String(coverage.N)));
  assert.ok(coverage.phrasing.includes(String(coverage.K)));
  assert.ok(coverage.phrasing.includes(baseline.detector_sha));
});

test("real repo end-to-end run against scripts/ + the real registry/baseline produces a well-formed report", () => {
  const result = runEnforcer({ root: "scripts", baseDir: REPO_ROOT });
  assert.ok(typeof result.exitCode === "number");
  assert.ok(Array.isArray(result.new_entrants));
  assert.ok(Array.isArray(result.regressed));
  assert.equal(result.regressed.length, 0); // no real row yet claims expected_finding: absent
});
